In [29]:
# Import library
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


#data = pd.read_clipboard()

In [14]:
data = pd.read_clipboard(sep=',')


In [15]:
data

Matematika  Seni  Olahraga  Teknologi     Bakat
0           88    58        64         85  Akademik
1           78    73        81         87   Atletik
2           64    50        81         89   Atletik
3           92    93        73         69      Umum
4           57    57        90         84   Atletik
..         ...   ...       ...        ...       ...
95          64    86        82         66  Artistik
96          94    82        73         89  Akademik
97          50    91        60         82  Artistik
98          74    93        98         58   Atletik
99          56    73        57         92      Umum

[100 rows x 5 columns]

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Matematika  100 non-null    int64 
 1   Seni        100 non-null    int64 
 2   Olahraga    100 non-null    int64 
 3   Teknologi   100 non-null    int64 
 4   Bakat       100 non-null    object
dtypes: int64(4), object(1)
memory usage: 4.0+ KB


In [31]:
data.empty

False

In [32]:
#ubah data bakat jd numerik
en = LabelEncoder()

data['Bakat'] = en.fit_transform(data['Bakat'])
data

Matematika  Seni  Olahraga  Teknologi  Bakat
0           88    58        64         85      0
1           78    73        81         87      2
2           64    50        81         89      2
3           92    93        73         69      3
4           57    57        90         84      2
..         ...   ...       ...        ...    ...
95          64    86        82         66      1
96          94    82        73         89      0
97          50    91        60         82      1
98          74    93        98         58      2
99          56    73        57         92      3

[100 rows x 5 columns]

In [33]:
#mnntukn dta x dn y
x = data.iloc[:, :-1].values #mngmbil nilai kcuali pd klom trakhir
y = data.iloc[:, -1].values #hny mngmbil nilai pd klom trakhir

In [34]:
x

array([[88, 58, 64, 85],
       [78, 73, 81, 87],
       [64, 50, 81, 89],
       [92, 93, 73, 69],
       [57, 57, 90, 84],
       [70, 73, 98, 97],
       [88, 60, 98, 74],
       [68, 66, 61, 84],
       [72, 57, 88, 74],
       [60, 84, 51, 78],
       [60, 84, 52, 67],
       [73, 82, 98, 95],
       [85, 54, 86, 67],
       [89, 91, 98, 51],
       [73, 88, 66, 84],
       [52, 90, 98, 65],
       [71, 77, 51, 90],
       [51, 56, 51, 85],
       [73, 58, 77, 82],
       [93, 57, 72, 53],
       [79, 61, 86, 82],
       [87, 83, 81, 63],
       [51, 82, 82, 70],
       [70, 97, 50, 97],
       [82, 72, 68, 69],
       [61, 73, 51, 57],
       [71, 86, 93, 56],
       [93, 84, 75, 52],
       [74, 93, 81, 66],
       [98, 89, 55, 82],
       [76, 71, 81, 97],
       [91, 76, 53, 61],
       [77, 84, 60, 71],
       [65, 50, 66, 71],
       [64, 84, 87, 95],
       [96, 86, 73, 79],
       [93, 96, 54, 87],
       [52, 63, 83, 87],
       [86, 52, 55, 94],
       [56, 50, 71, 57],


In [35]:
y

array([0, 2, 2, 3, 2, 2, 2, 3, 2, 1, 1, 2, 2, 2, 3, 1, 3, 3, 3, 3, 2, 2,
       1, 3, 3, 3, 2, 3, 2, 0, 2, 3, 3, 3, 1, 3, 0, 2, 0, 3, 3, 2, 0, 1,
       3, 3, 3, 0, 3, 3, 2, 1, 3, 0, 1, 3, 2, 3, 2, 1, 1, 2, 0, 0, 1, 3,
       1, 0, 2, 3, 3, 3, 2, 0, 3, 0, 1, 2, 2, 3, 3, 2, 3, 0, 2, 2, 0, 2,
       2, 3, 2, 3, 0, 3, 3, 1, 0, 1, 2, 3])

In [36]:
#splitting data
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=123)

print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))

x_train =  80
x_test =  20
y_train =  80
y_test =  20


In [37]:
#pengskalaan nilai pada data pke standard scaller

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [38]:
x_train 

array([[ 1.43552379,  0.8118026 ,  0.02982013,  0.18548812],
       [ 1.43552379,  1.10140888,  0.75875666, -0.42643145],
       [ 1.23333734, -1.28784293, -0.03644683, -1.80325047],
       [ 1.57031476,  1.02900731, -1.1629851 ,  0.41495795],
       [ 1.09854638,  0.0877869 , -1.29551901, -1.1913309 ],
       [-0.04717684, -1.43264607, -0.50031553, -0.04398172],
       [-0.65373619, -1.79465392,  0.55995579,  1.71528703],
       [-0.9907136 ,  0.66699946, -1.42805292,  0.10899817],
       [ 1.43552379,  1.68062144, -1.36178597,  0.56793785],
       [-1.12550457,  0.01538533,  1.6202271 , -0.04398172],
       [ 0.82896444,  0.59459789,  0.55995579, -1.03835101],
       [ 0.02021864,  0.95660574,  1.6202271 , -1.95623036],
       [-0.65373619, -1.79465392, -0.43404857, -0.42643145],
       [ 0.22240509,  0.16018847, -0.03644683,  0.26197806],
       [-0.31675877,  0.52219632,  0.89129057, -0.27345156],
       [-0.51894522, -0.92583508,  1.1563584 ,  1.48581719],
       [-0.72113167,  0.

In [39]:
x_test

array([[-0.1819678 , -1.28784293,  1.02382449, -0.19696161],
       [-0.51894522, -1.72225235,  0.49368883,  0.56793785],
       [-0.1819678 , -0.05701624, -0.76538335,  0.95038757],
       [-0.04717684,  1.31861359,  0.55995579, -0.80888117],
       [ 0.96375541,  0.23259004,  1.09009144,  1.02687752],
       [ 0.89635993, -1.21544136, -0.56658248,  0.64442779],
       [-0.31675877, -0.12941781,  1.68649406,  1.56230714],
       [-1.59727295, -0.92583508,  0.82502362,  1.56230714],
       [-0.78852715,  0.16018847,  1.6202271 , -1.87974041],
       [-1.19290005, -1.28784293,  1.1563584 ,  0.56793785],
       [-0.31675877,  1.60821987, -1.49431988,  1.56230714],
       [-1.59727295, -0.92583508, -0.83165031, -0.27345156],
       [-0.78852715,  1.31861359,  0.16235404, -1.87974041],
       [-0.5863407 ,  1.39101516,  1.09009144,  1.40932725],
       [ 0.49198703, -0.20181938, -0.30151465, -0.57941134],
       [ 0.89635993, -0.85343351, -0.50031553,  0.4914479 ],
       [ 0.35719606,  1.

In [40]:
y_train

array([3, 2, 3, 0, 3, 3, 2, 1, 0, 2, 2, 2, 3, 3, 2, 2, 1, 1, 0, 2, 2, 3,
       2, 1, 2, 3, 2, 3, 3, 1, 3, 2, 1, 3, 2, 2, 2, 3, 2, 1, 1, 3, 3, 2,
       1, 1, 2, 3, 1, 3, 3, 1, 3, 3, 3, 3, 2, 3, 3, 3, 2, 0, 3, 3, 2, 3,
       0, 2, 0, 3, 3, 3, 0, 0, 0, 3, 0, 3, 0, 1])

In [41]:
y_test

array([2, 3, 3, 2, 0, 0, 2, 2, 2, 2, 3, 3, 1, 1, 3, 0, 2, 0, 2, 0])

In [42]:
#training model pke nb

classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [43]:
#prediksi
y_pred = classifier.predict(x_test)
y_pred

array([2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 3, 3, 3, 2, 3, 3, 2, 0, 1, 3])

In [44]:
#predik probabilitas
classifier.predict_proba(x_test)

array([[1.06479779e-07, 5.68443579e-17, 9.60560060e-01, 3.94398337e-02],
       [3.22406068e-08, 4.11464195e-23, 5.50635837e-01, 4.49364131e-01],
       [3.41781584e-05, 8.73361978e-04, 1.49905620e-04, 9.98942554e-01],
       [1.74467625e-07, 2.16482656e-02, 7.11511990e-01, 2.66839570e-01],
       [1.70844322e-01, 8.70385073e-07, 8.21076123e-01, 8.07868404e-03],
       [5.45107574e-01, 7.36196805e-20, 3.30522489e-04, 4.54561903e-01],
       [3.63524972e-08, 1.60985485e-04, 9.99221308e-01, 6.17670419e-04],
       [9.08743820e-20, 1.16343540e-10, 9.33163849e-01, 6.68361505e-02],
       [2.84011968e-19, 1.96290953e-02, 9.78573833e-01, 1.79707192e-03],
       [1.59039758e-15, 1.41169509e-15, 9.77252134e-01, 2.27478662e-02],
       [1.65423670e-05, 4.40886395e-03, 2.41597300e-07, 9.95574352e-01],
       [8.38834392e-21, 8.65291922e-11, 2.32579649e-05, 9.99976742e-01],
       [2.15402826e-17, 1.98133044e-01, 1.40098435e-01, 6.61768521e-01],
       [2.99219436e-09, 4.29005563e-02, 9.48678753e

In [45]:
#evaluasi
#confusion matriks
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2 0 1 2]
 [0 0 1 1]
 [0 1 7 0]
 [0 0 1 4]]


In [46]:
#evaluasi
#clasification report
akurasi = classification_report(y_test, y_pred)
akurasi

'              precision    recall  f1-score   support\n\n           0       1.00      0.40      0.57         5\n           1       0.00      0.00      0.00         2\n           2       0.70      0.88      0.78         8\n           3       0.57      0.80      0.67         5\n\n    accuracy                           0.65        20\n   macro avg       0.57      0.52      0.50        20\nweighted avg       0.67      0.65      0.62        20\n'

In [47]:
#lht akurasi 
akurasi = accuracy_score(y_test, y_pred)
print("tingkat akurasi = %d persen"%(akurasi*100))

tingkat akurasi = 65 persen


In [48]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)

ydata

y_test  y_pred
0        2       2
1        3       2
2        3       3
3        2       2
4        0       2
5        0       0
6        2       2
7        2       2
8        2       2
9        2       2
10       3       3
11       3       3
12       1       3
13       1       2
14       3       3
15       0       3
16       2       2
17       0       0
18       2       1
19       0       3